const requests = [
    {
    requestID: "TR-001",
    requestor: "John Doe",
    destination: "New York, USA",
    startDate: "08/15/2026",
    endDate: "08/20/2026",
    estimatedCost: "$2,500",
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Attending a business conference on emerging technologies.",
    }, 

    {
    requestID: "TR-002",
    requestor: "Jane Smith",
    destination: "Tokyo, Japan",
    startDate: "09/10/2026",
    endDate: "09/15/2026",
    estimatedCost: "$3,200",
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Meeting with potential clients and partners in the tech industry.",
    },

    {
    requestID: "TR-003",
    requestor: "Michael Johnson",
    destination: "Berlin, Germany",
    startDate: "10/05/2026",
    endDate: "10/10/2026",
    estimatedCost: "$2,800",
    status: "Rejected",
    statusIcon: "../Images/Icons/red_status.png",
    purposeForTravel: "Attending a trade show for software development tools.",
    },

    {
    requestID: "TR-004",
    requestor: "Emily Davis",
    destination: "Sydney, Australia",
    startDate: "11/12/2026",
    endDate: "11/18/2026",
    estimatedCost: "$4,000",
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Participating in a workshop on digital marketing strategies.",
    }, 

    {
    requestID: "TR-005",
    requestor: "David Wilson",
    destination: "Paris, France",
    startDate: "12/01/2026",
    endDate: "12/07/2026",
    estimatedCost: "$3,500",
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Attending a fashion industry seminar and networking event.",
    },

    {
    requestID: "TR-006",
    requestor: "Sarah Lee",
    destination: "Rome, Italy",
    startDate: "01/15/2027",
    endDate: "01/20/2027",
    estimatedCost: "$13,000",
    status: "New Request",
    statusIcon: "../Images/Icons/yellow_status.png",
    purposeForTravel: "Exploring potential business opportunities in the European market.",
    }, 

    {
    requestID: "TR-007",
    requestor: "Chris Brown",
    destination: "Barcelona, Spain",
    startDate: "02/10/2027",
    endDate: "02/15/2027",
    estimatedCost: "$2,700",
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Attending a technology summit and meeting with industry experts.",
    },

    {
    requestID: "TR-008",
    requestor: "Olivia Martinez",
    destination: "Cape Town, South Africa",
    startDate: "03/05/2027",
    endDate: "03/10/2027",
    estimatedCost: "$15,800",
    status: "Rejected",
    statusIcon: "../Images/Icons/red_status.png",
    purposeForTravel: "Conducting market research for a new product launch in the African market.",
    },

    {
    requestID: "TR-009",
    requestor: "Daniel Anderson",
    destination: "Rio de Janeiro, Brazil",
    startDate: "04/12/2027",
    endDate: "04/18/2027",
    estimatedCost: "$3,900",
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Attending a sports industry conference and networking with professionals.",
    },

    {
    requestID: "TR-010",
    requestor: "Sophia Taylor",
    destination: "Dubai, UAE",
    startDate: "05/01/2027",
    endDate: "05/07/2027",
    estimatedCost: "$5,200",
    status: "New Request",
    statusIcon: "../Images/Icons/yellow_status.png",
    purposeForTravel: "Exploring potential partnerships and investment opportunities in the Middle East.",
    }, 

    {
    requestID: "TR-011",
    requestor: "William Harris",
    destination: "Singapore",
    startDate: "06/15/2027",
    endDate: "06/20/2027",
    estimatedCost: "$4,500",
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Attending a technology expo and meeting with industry leaders.",
    }, 

    {
    requestID: "TR-012",
    requestor: "Ava Clark",
    destination: "Bangkok, Thailand",
    startDate: "07/10/2027",
    endDate: "07/15/2027",
    estimatedCost: "$13,800",
    status: "Rejected", 
    statusIcon: "../Images/Icons/red_status.png",
    purposeForTravel: "Conducting market research for a new product launch in Southeast Asia.",
    },

    {
    requestID: "TR-013",
    requestor: "James Lewis",
    destination: "Istanbul, Turkey",
    startDate: "08/05/2027",
    endDate: "08/10/2027",
    estimatedCost: "$3,600",
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Attending a business conference on emerging markets and investment opportunities.",
    }
    

]