const requests = [
    {
    requestID: "TR-001",
    requestor: "John Doe",
    approver: "Alyssa Hughes",
    destination: "New York, USA",
    startDate: "2026-12-24",
    endDate: "2026-12-29",
    estimatedCost: 2500,
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Attending a business conference on emerging technologies.",
    }, 

    {
    requestID: "TR-002",
    requestor: "Jane Smith",
    approver: "John Doe",
    destination: "Tokyo, Japan",
    startDate: "2026-11-15",
    endDate: "2026-11-16",
    estimatedCost: 3200,
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Meeting with potential clients and partners in the tech industry.",
    },

    {
    requestID: "TR-003",
    requestor: "Michael Johnson",
    approver: "Alyssa Hughes",
    destination: "Berlin, Germany",
    startDate: "2026-05-19",
    endDate: "2026-05-20",
    estimatedCost: 2800,
    status: "Rejected",
    statusIcon: "../Images/Icons/red_status.png",
    purposeForTravel: "Attending a trade show for software development tools.",
    },

    {
    requestID: "TR-004",
    requestor: "Emily Davis",
    approver: "John Doe",
    destination: "Sydney, Australia",
    startDate: "2026-06-21",
    endDate: "2026-06-25",
    estimatedCost: 4000,
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Participating in a workshop on digital marketing strategies.",
    }, 

    {
    requestID: "TR-005",
    requestor: "David Wilson",
    approver: "Alyssa Hughes",
    destination: "Paris, France",
    startDate: "2026-08-06",
    endDate: "2026-08-14",
    estimatedCost: 3500,
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Attending a fashion industry seminar and networking event.",
    },

    {
    requestID: "TR-006",
    requestor: "Sarah Lee",
    approver: "John Doe",
    destination: "Rome, Italy",
    startDate: "2026-08-14",
    endDate: "2026-08-19",
    estimatedCost: 13000,
    status: "New Request",
    statusIcon: "../Images/Icons/yellow_status.png",
    purposeForTravel: "Exploring potential business opportunities in the European market.",
    }, 

    {
    requestID: "TR-007",
    requestor: "Chris Brown",
    approver: "Alyssa Hughes",
    destination: "Barcelona, Spain",
    startDate: "2026-10-10",
    endDate: "2026-10-17",
    estimatedCost: 2700,
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Attending a technology summit and meeting with industry experts.",
    },

    {
    requestID: "TR-008",
    requestor: "Olivia Martinez",
    approver: "John Doe",
    destination: "Cape Town, South Africa",
    startDate: "2026-07-25",
    endDate: "2026-07-28",
    estimatedCost: 15800,
    status: "Rejected",
    statusIcon: "../Images/Icons/red_status.png",
    purposeForTravel: "Conducting market research for a new product launch in the African market.",
    },

    {
    requestID: "TR-009",
    requestor: "Daniel Anderson",
    approver: "Alyssa Hughes",
    destination: "Rio de Janeiro, Brazil",
    startDate: "2026-08-14",
    endDate: "2026-08-16",
    estimatedCost: 3900,
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Attending a sports industry conference and networking with professionals.",
    },

    {
    requestID: "TR-010",
    requestor: "Sophia Taylor",
    approver: "John Doe",
    destination: "Dubai, UAE",
    startDate: "2026-08-07",
    endDate: "2026-08-14",
    estimatedCost: 5200,
    status: "New Request",
    statusIcon: "../Images/Icons/yellow_status.png",
    purposeForTravel: "Exploring potential partnerships and investment opportunities in the Middle East.",
    }, 

    {
    requestID: "TR-011",
    requestor: "William Harris",
    approver: "Alyssa Hughes",
    destination: "Singapore",
    startDate: "2026-08-14",
    endDate: "2026-08-23",
    estimatedCost: 4500,
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Attending a technology expo and meeting with industry leaders.",
    }, 

    {
    requestID: "TR-012",
    requestor: "Ava Clark",
    approver: "John Doe",
    destination: "Bangkok, Thailand",
    startDate: "2026-09-15",
    endDate: "2026-09-20",
    estimatedCost: 13800,
    status: "Rejected", 
    statusIcon: "../Images/Icons/red_status.png",
    purposeForTravel: "Conducting market research for a new product launch in Southeast Asia.",
    },

    {
    requestID: "TR-013",
    requestor: "James Lewis",
    approver: "John Doe",
    destination: "Istanbul, Turkey",
    startDate: "2026-08-25",
    endDate: "2026-08-85",
    estimatedCost: 3600,
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Attending a business conference on emerging markets and investment opportunities.",
    },

    {
    requestID: "TR-014",
    requestor: "Mia Walker",
    approver: "Alyssa Hughes",
    destination: "Lisbon, Portugal",
    startDate: "2026-08-05",
    endDate: "2026-08-14",
    estimatedCost: 2500,
    status: "Pending Approval",
    statusIcon: "../Images/Icons/blue_status.png",
    purposeForTravel: "Attending a business conference on emerging technologies.",
    },

    {
    requestID: "TR-015",
    requestor: "Liam Hall",
    approver: "John Doe",
    destination: "Vienna, Austria",
    startDate: "2026-08-14",
    endDate: "2026-08-25",
    estimatedCost: 3000,
    status: "Approved",
    statusIcon: "../Images/Icons/green_status.png",
    purposeForTravel: "Attending a business conference on emerging technologies.",
    }
    

]